/** Must match App\Support\NavSections::labels() keys (dashboard is always on for everyone). */
export const NAV_SECTION_OPTIONS = [
    { key: 'dashboard', label: 'Dashboard' },
    { key: 'appointments', label: 'Appointments' },
    { key: 'followups', label: 'Follow-ups' },
    { key: 'prospects', label: 'Prospects' },
    { key: 'customers', label: 'Customers' },
    { key: 'all_leads', label: 'All Leads' },
    { key: 'lead_pipeline', label: 'Lead Pipeline' },
    { key: 'products', label: 'Products' },
    { key: 'tickets', label: 'Tickets' },
    { key: 'pos_support', label: 'POS Support' },
    { key: 'invoices', label: 'Invoices' },
    { key: 'today_activity', label: "Today's Activity" },
    { key: 'report', label: 'Report (submenu)' },
    { key: 'todays_report', label: "Today's Report" },
    { key: 'marketing', label: 'Marketing (submenu)' },
    { key: 'employees', label: 'Employees' },
    { key: 'hr', label: 'HR' },
    { key: 'expenses', label: 'Expenses' },
    { key: 'salary_slips', label: 'Salary Slips' },
    { key: 'salary_reports', label: 'Salary Reports' },
    { key: 'settings', label: 'Settings' },
    { key: 'access_manager', label: 'Access Manager' },
];
